"""All texts of the GUI. Use t("key", name=value). Add a language by adding a dict with the same keys."""
from __future__ import annotations

LANGUAGE = "de"

STRINGS: dict[str, dict[str, str]] = {
    "de": {
        "app.title": "realcam",
        "drop.title": "Videos oder einen Ordner hier hineinziehen",
        "drop.hint": "Ein Ordner wird zur Warteschlange: jede Datei wird einzeln verarbeitet.",
        "drop.choose_files": "Videos wählen …",
        "drop.choose_folder": "Ordner wählen …",
        "drop.dialog_files": "Videos wählen",
        "drop.dialog_folder": "Ordner mit Videos wählen",
        "drop.file_filter": "Videos ({patterns})",
        "drop.none_found": "Keine Videodateien gefunden.",
        "drop.skipped": "{count} Datei(en) übersprungen (kein Video oder nicht lesbar).",
        "list.col_name": "Datei",
        "list.col_size": "Auflösung",
        "list.col_fps": "Bilder/s",
        "list.col_duration": "Dauer",
        "list.col_bitrate": "Bitrate",
        "list.col_notes": "Hinweise",
        "list.notes_count": "{count} Hinweis(e)",
        "list.bitrate_unknown": "unbekannt",
        "details.title": "Hinweise zur Datei",
        "details.none": "Keine Auffälligkeiten.",
        "details.select": "Datei in der Liste auswählen, um die Hinweise zu sehen.",
        "preflight.title": "Systemprüfung",
        "preflight.running": "Prüfe FFmpeg, Modelle und Grafikkarte …",
        "preflight.all_ok": "Alles bereit.",
        "preflight.blocked": "Rendern ist erst möglich, wenn die Fehler behoben sind.",
        "preflight.recheck": "Erneut prüfen",
        "preflight.ffmpeg.ok": "FFmpeg gefunden: {path}",
        "preflight.ffmpeg.missing": "FFmpeg oder ffprobe wurde nicht gefunden. Installieren mit „winget install -e --id Gyan.FFmpeg“ und das Programm danach neu starten.",
        "preflight.weights.ok": "Modellgewichte vollständig ({count} Dateien in {folder}).",
        "preflight.weights.missing": "Modellgewichte fehlen in {folder}: {files}. Anleitung zum Herunterladen: README.md, Abschnitt „Model weights“.",
        "preflight.weights.wrong_size": "Modelldatei {file} hat {found} statt {expected} Bytes und ist vermutlich unvollständig. Neu laden: README.md, Abschnitt „Model weights“.",
        "preflight.cuda.failed": "Die Grafikkartenprüfung ist fehlgeschlagen: {detail}",
        "preflight.cuda.timeout": "Die Grafikkartenprüfung hat nach {seconds} Sekunden nicht geantwortet.",
        "preflight.cuda.no_gpu": "Dieses Programm braucht eine NVIDIA-Grafikkarte (RTX 20 oder neuer). Mit AMD, Intel oder Mac läuft es nicht. Falls Sie eine besitzen: Treiber prüfen („nvidia-smi“) und ob PyTorch mit CUDA installiert ist.",
        "preflight.cuda.gpu_old": "Ihre Grafikkarte ({name}) ist zu alt. Benötigt wird mindestens eine RTX 20 oder GTX 16.",
        "preflight.cuda.ok": "Grafikkarte: {name}, {vram} GB Speicher, PyTorch {torch}.",
        "preflight.driver.old": "Ihr NVIDIA-Treiber ({version}) ist zu alt. Benötigt wird Version {minimum} oder neuer. Bitte aktualisieren und den PC neu starten.",
        "preflight.driver.unknown": "Die Version des NVIDIA-Treibers konnte nicht ermittelt werden („nvidia-smi“ nicht gefunden).",
        "preflight.vram.low": "Es wurden nur {vram} GB Grafikspeicher erkannt. Empfohlen sind {recommended} GB. Mit weniger kann das Rendern abbrechen.",
        "preflight.av1.missing": "Ihre Karte kann kein AV1. Es muss HEVC verwendet werden.",
        "preflight.disk.ok": "Freier Speicher reicht: {free} GB frei auf {drive}.",
        "preflight.disk.low": "Für dieses Video werden etwa {needed} GB frei benötigt, auf {drive} sind {free} GB frei.",
        "preflight.disk.unknown": "Der freie Speicher auf {drive} konnte nicht ermittelt werden.",
        "preflight.disk.no_video": "Freier Speicher: wird geprüft, sobald ein Video geladen ist.",
        "warn.low_res": "Die Quelle hat nur {width}×{height}. Alle Tests liefen mit 1440p-Quellen; kleinere Quellen werden stärker hochskaliert, das Ergebnis ist ungetestet.",
        "warn.low_bitrate": "Die Bitrate der Quelle beträgt {bitrate} Mbit/s. Getestet wurden Quellen ab {tested} Mbit/s; bei weniger sind Blockartefakte im Original möglich, die das Ergebnis verstärken kann.",
        "warn.fps": "Die Quelle hat {fps} Bilder pro Sekunde statt {expected}. Die Ausgabe hat 60 Bilder pro Sekunde; das Ergebnis ist für andere Raten ungetestet.",
        "warn.vfr": "Variable Bildrate erkannt. Die Quelle wird beim Einlesen auf die höchste Rate ({fps} Bilder/s) umgerechnet, fehlende Bilder werden wiederholt.",
        "warn.hdr": "HDR-Quelle erkannt. HDR wird nicht unterstützt, die Farben werden falsch. Benötigt wird SDR (BT.709).",
        "estimate.under_minute": "unter 1 Min.",
        "estimate.minutes": "{minutes} Min.",
        "estimate.hours_minutes": "{hours} Std. {minutes:02d} Min.",
        "estimate.range": "{low} – {high}",
        "render.cancelled": "Abgebrochen. Fertige Segmente ({done} von {total}) bleiben erhalten, das laufende Segment ist verloren. „Fortsetzen“ rechnet ab dem nächsten fehlenden Segment weiter.",
        "render.paused": "Pausiert nach Segment {done} von {total}. Alle fertigen Segmente bleiben erhalten; „Fortsetzen“ rechnet weiter.",
        "render.exit_code": "Der Rechenprozess wurde unerwartet beendet (Code {code}).",
        "render.failed": "Fehler: {reason}",
        "render.verify_failed": "Die fertige Datei besteht die Prüfung nicht: {problems}. Der Zwischenordner bleibt erhalten.",
        "render.work_kept": "Der Zwischenordner wurde nicht gelöscht.",
        "render.work_removed": "Der Zwischenordner wurde gelöscht.",
        "render.done": "Fertig: {out}.",
        "render.closed": "Das Fenster wurde während des Renderns geschlossen. Fertige Segmente bleiben erhalten; beim nächsten Start kann der Job fortgesetzt werden.",
        "verify.missing": "Die Ausgabedatei fehlt oder ist leer: {path}",
        "verify.unreadable": "Die Ausgabedatei ist nicht lesbar: {path}",
        "verify.size": "Auflösung {found} statt {expected}",
        "verify.frames": "{found} statt {expected} Bilder",
        "verify.duration": "Dauer {found} s statt {expected} s",
        "verify.no_ffprobe": "ffprobe fehlt, die Ausgabe konnte nicht geprüft werden",
        "resume.source_missing": "Die Quelldatei ist nicht mehr vorhanden. Fortsetzen ist nicht möglich.",
        "resume.source_changed": "Die Quelldatei wurde seit dem Start verändert. Fortsetzen ist nicht möglich; ein neuer Lauf wäre ein neuer Job.",
        "resume.work_missing": "Der Zwischenordner des Jobs fehlt. Fortsetzen ist nicht möglich.",
        "start.lock_held": "Es läuft bereits ein Render oder eine Vorschau in diesem Programm (Prozess {pid}). Es darf immer nur einer gleichzeitig rechnen.",
        "start.external_running": "Ein anderer Lauf von enhance.py ist aktiv (Prozess {pid}). Bitte warten, bis er fertig ist; zwei Läufe gleichzeitig auf der Grafikkarte sind nicht erlaubt.",
        "start.next": "Weiter zu den Looks",
        "banner.text": "Unfertiger Job: {name} ({look}), {done} von {total} Segmenten fertig.",
        "banner.resume": "Unfertigen Job fortsetzen",
        "banner.discard": "Verwerfen",
        "card.back": "Zurück",
        "card.render": "Rendern",
        "card.quality_lite": "Standard (export-lite)",
        "card.quality_ai": "KI (export)",
        "card.quality_lite_short": "Standard",
        "card.quality_ai_short": "KI",
        "card.ai_warning": "Achtung: Die KI kann Texturen wie Leder verändern. Sie hilft vor allem bei Schrift und Kennzeichen.",
        "card.showroom.title": "Showroom",
        "card.showroom.desc": "Scharf und knackig: kräftiger Kontrast, mehr Klarheit und Schärfung.",
        "card.subtle.title": "Subtle",
        "card.subtle.desc": "Leichtes Grading, kaum Linseneffekte, feines Korn.",
        "card.cinematic.title": "Cinematic",
        "card.cinematic.desc": "Kamera-Look komplett: Farbstimmung, Weichzeichnung, Bloom, Halation, Vignette und Korn.",
        "card.dashcam.title": "Dashcam-real",
        "card.dashcam.desc": "Dashcam-Anmutung: stärkeres Korn, flacheres Bild, weniger Kontrast.",
        "card.none.title": "Ohne Look",
        "card.none.desc": "Nur Hochskalierung auf 2160p60 mit Entblockung und Bewegungsunschärfe, kein Look.",
        "preview.busy": "Es läuft bereits eine Vorschau oder ein Render in diesem Programm (Prozess {pid}). Die Grafikkarte rechnet immer nur einen Lauf.",
        "preview.failed": "Vorschau fehlgeschlagen: {reason}",
        "preview.no_image": "Aus dem Ergebnis konnte kein Bild geschnitten werden: {detail}",
        "preview.no_output": "Es wurde keine Ausgabedatei erzeugt.",
        "preview.stage_base": "Berechne … Basis (Grafikkarte)",
        "preview.stage_look": "Berechne … Bild {n} von {of}",
        "preview.stage_original": "Berechne … Original",
        "preview.original": "Original",
        "preview.result": "Ergebnis",
        "preview.position": "Position:",
        "preview.pos_button": "{n} · {time}",
        "preview.cancel": "Vorschau abbrechen",
        "preview.grain_hint": "Hinweis: Korn-Looks (Subtle, Cinematic, Dashcam-real) wirken in der Vorschau stärker als im Endergebnis, weil der Encoder das Korn abschwächt. Die Vorschau zeigt das Bild vor dem Encoder. Das Original ist zum Vergleich auf dieselbe Größe hochgerechnet.",
        "preview.searching": "Suche geeignete Positionen …",
        "preview.moved": "Position verändert – loslassen, dann wird gerechnet.",
        "preview.computing": "Berechne …",
        "preview.queued": "Wartet auf die Berechnung …",
        "preview.not_computed": "Noch nicht berechnet. Eine Position wählen, dann wird gerechnet.",
        "preview.failed_short": "Fehlgeschlagen.",
        "preview.short": "Kurzvorschau (5 s)",
        "preview.short_estimate": "Kurzvorschau (5 s): ca. {time}",
        "preview.short_busy": "Es wird gerade eine Vorschau berechnet. Bitte warten oder „Vorschau abbrechen“ klicken.",
        "preview.short_running": "Kurzvorschau rechnet … {percent} %",
        "preview.short_done": "Kurzvorschau fertig und im Standard-Player geöffnet: {path}",
        "zoom.title": "Zoom 100 % – {look}",
        "zoom.original": "Vorher (Original)",
        "zoom.result": "Nachher (Ergebnis)",
        "zoom.hint": "Mit der Maus ziehen oder Pfeiltasten: beide Bilder bewegen sich gemeinsam. Leertaste: Vorher/Nachher.",
        "zoom.switch": "Vorher/Nachher",
        "zoom.mode_switch": "Einzelbild",
        "zoom.mode_side": "Nebeneinander",
        "zoom.showing_original": "Zeige: Vorher (Original)",
        "zoom.showing_result": "Zeige: Nachher (Ergebnis)",
        "estimate.time": "Renderzeit: {range}",
        "estimate.basis": "ca., auf RTX 4070 gemessen",
        "estimate.disk": "Speicherbedarf: ca. {gb} GB (Ausgabe und Zwischenordner)",
        "render.title": "{name}: {look}, {quality}",
        "render.segment": "Segment {segment} von {segments}",
        "render.eta": "Restzeit ca. {eta}",
        "render.checking": "Prüfe, ob bereits ein Lauf aktiv ist …",
        "render.starting": "Starte …",
        "render.running": "Rechnet. Die Grafikkarte ist belegt, bitte nichts anderes darauf rechnen lassen.",
        "render.concat": "Füge die Segmente zusammen … (Pause ist jetzt nicht mehr sinnvoll)",
        "render.finalizing": "Prüfe die fertige Datei …",
        "render.pause_requested": "Pause nach diesem Segment ist angefordert. Das laufende Segment wird noch fertig gerechnet.",
        "render.pause_too_late": "Pause ist nicht mehr möglich: der letzte Abschnitt läuft bereits, der Render schließt jetzt ab.",
        "render.lost": "Verloren: {lost} Rechenzeit im laufenden Segment.",
        "render.start_failed": "Der Rechenprozess konnte nicht gestartet werden: {reason}",
        "render.awake_note": "Der Computer bleibt wach, solange gerendert wird.",
        "render.btn_cancel": "Abbrechen",
        "render.btn_pause": "Pause nach diesem Segment",
        "render.btn_resume": "Fortsetzen",
        "render.btn_open": "Ausgabeordner öffnen",
        "render.btn_back": "Zurück zum Start",
        "cancel.confirm_title": "Rendern abbrechen?",
        "cancel.confirm": "Verloren geht das laufende Segment (bisher {current} Rechenzeit, höchstens ca. {maximum}). {kept} fertige Segmente bleiben erhalten, „Fortsetzen“ rechnet danach weiter.",
        "close.confirm_title": "Programm beenden?",
        "close.confirm": "Es wird noch gerendert. Beim Beenden geht das laufende Segment verloren; fertige Segmente bleiben, der Job kann beim nächsten Start fortgesetzt werden.",
        "error.not_found": "Datei nicht gefunden: {path}",
        "error.unreadable": "Datei nicht lesbar oder defekt: {path}",
        "error.no_video_stream": "Kein Videostream in {path}.",
        "error.no_ffprobe": "ffprobe wurde nicht gefunden.",
    },
}


DECIMAL_SEPARATOR = {"de": ","}


def number(value: float, digits: int = 1, trim: bool = False) -> str:
    """Format a number with the decimal separator of the active language."""
    text = f"{value:.{digits}f}"
    if trim and "." in text:
        text = text.rstrip("0").rstrip(".")
    return text.replace(".", DECIMAL_SEPARATOR.get(LANGUAGE, "."))


def t(key: str, **values: object) -> str:
    """Look up a text in the active language and fill in the placeholders."""
    text = STRINGS[LANGUAGE][key]
    return text.format(**values) if values else text
